### ISSUE TITLE
[REG] new material

### ISSUE THREAD

**Issue by annhat-ux** [NanoCommons/identifiers#24]
# Required information

- Name or Label: Momentum PVC leachate

# Optional information

- Parent identifier (identifier of the material that this material was derived from): CAS: 71-23-8
- Project name: Momentum

**Comment by egonw** [comment]
@annhat-ux, thanks!

Just to make sure, if you need more than a few, or even more than one, you can open all report this in just one issue report, to minimize your/the work. I'll create the two you now requested during today.

**Comment by egonw** [comment]
@annhat-ux, to make sure, this project, right? https://cordis.europa.eu/project/id/815069

**Comment by annhat-ux** [comment]
@egonw, thanks for double-checking. This is the project: https://momentummicroplastics.nl/

**Comment by egonw** [comment]
This one is: erm:ERM00000663

**Comment by egonw** [comment]
One more question, is the CAS registry number correct? https://commonchemistry.cas.org/detail?cas_rn=71-23-8&search=71-23-8 does not sounds like an easy material to make materials from.

**Comment by annhat-ux** [comment]
This is what the researcher wrote me about it "I think for the CAS number we can best use that of 1-propanol (71-23-8) because that’s what they [the leachates] mainly contain".

**Comment by annhat-ux** [comment]
Thanks for generating an ID for them!

**Comment by egonw** [comment]
Closed by https://github.com/NanoCommons/identifiers/commit/849ca8dcd291f1febb223385a92ed1a92c73de5c
